# Generated by Django 2.2 on 2019-11-15 07:16

import MeinPage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_address', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('inclusive', models.CharField(max_length=255)),
                ('meal_type', models.CharField(max_length=255)),
                ('amenities', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cities', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Start_date', models.CharField(max_length=255)),
                ('End_date', models.CharField(max_length=255)),
                ('Flight_inbound', models.CharField(max_length=255)),
                ('Flight_outbound', models.CharField(max_length=255)),
                ('Flight_prise', models.CharField(max_length=255)),
                ('Land_prise', models.CharField(max_length=255)),
                ('Totel_prise', models.CharField(max_length=255)),
                ('Activities_include', models.CharField(max_length=255)),
                ('Visa_included', models.CharField(max_length=255)),
                ('Acivities_included', models.CharField(max_length=255)),
                ('Exclusive', models.CharField(max_length=255)),
                ('Meal_included', models.CharField(max_length=255)),
                ('Itnerary', models.TextField()),
                ('Company_details', models.CharField(max_length=255)),
                ('Transfer_detail', models.CharField(max_length=255)),
                ('Freebies', models.CharField(max_length=255)),
                ('Transfer_detail_seperate', models.CharField(max_length=255)),
                ('seperate_sic_or_private', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('hot_deal_package', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('city', models.CharField(blank=True, max_length=30)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('phone', models.CharField(max_length=10)),
                ('termsAccepted', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', MeinPage.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Token_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('reset_token', models.CharField(max_length=6)),
                ('time', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='')),
                ('image_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_package', to='MeinPage.Package')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='')),
                ('image_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_hotel', to='MeinPage.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='MeinPage.Package'),
        ),
    ]
