# Generated by Django 2.2 on 2019-11-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_data',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
