# Generated by Django 2.2 on 2019-11-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='hot_deal_package',
            field=models.BooleanField(),
        ),
    ]
