# Generated by Django 2.2 on 2019-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0002_auto_20191111_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='ip',
            field=models.CharField(default='122332423423423', max_length=20),
            preserve_default=False,
        ),
    ]
