# Generated by Django 2.2 on 2019-11-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0002_auto_20191112_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_address', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('inclusive', models.CharField(max_length=255)),
                ('meal_type', models.CharField(max_length=255)),
                ('amenities', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cities', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Start_date', models.CharField(max_length=255)),
                ('End_date', models.CharField(max_length=255)),
                ('Flight_inbound', models.CharField(max_length=255)),
                ('Flight_outbound', models.CharField(max_length=255)),
                ('Flight_prise', models.CharField(max_length=255)),
                ('Land_prise', models.CharField(max_length=255)),
                ('Totel_prise', models.CharField(max_length=255)),
                ('Activities_include', models.CharField(max_length=255)),
                ('Visa_included', models.CharField(max_length=255)),
                ('Acivities_included', models.CharField(max_length=255)),
                ('Exclusive', models.CharField(max_length=255)),
                ('Meal_included', models.CharField(max_length=255)),
                ('Itnerary', models.TextField()),
                ('Company_details', models.CharField(max_length=255)),
                ('Transfer_detail', models.CharField(max_length=255)),
                ('Freebies', models.CharField(max_length=255)),
                ('Transfer_detail_seperate', models.CharField(max_length=255)),
                ('seperate_sic_or_private', models.CharField(max_length=255)),
                ('Hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeinPage.Hotel')),
            ],
        ),
    ]
