# Generated by Django 2.2 on 2019-11-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0003_token_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='ip',
            new_name='ip_add',
        ),
    ]
