# Generated by Django 2.2 on 2019-11-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0003_auto_20191116_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_city',
            name='hotel_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_city', to='MeinPage.Package'),
        ),
    ]
