# Generated by Django 2.2 on 2019-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0004_auto_20191111_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='ip_add',
        ),
        migrations.AddField(
            model_name='token',
            name='email',
            field=models.CharField(default='golu@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
