# Generated by Django 2.2 on 2019-11-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0004_auto_20191116_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_city',
            old_name='city_data',
            new_name='package_city',
        ),
        migrations.RenameField(
            model_name='package_city',
            old_name='hotel_city',
            new_name='package_city_id',
        ),
    ]
