# Generated by Django 2.2 on 2019-11-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0004_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='raju.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
