# Generated by Django 2.2 on 2019-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0005_auto_20191116_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_city',
            name='package_city',
            field=models.CharField(max_length=50),
        ),
    ]
