# Generated by Django 2.2 on 2019-11-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0005_auto_20191111_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Token_data',
        ),
    ]
