# Generated by Django 2.2 on 2019-12-02 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0006_auto_20191112_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='review', max_length=20)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_inbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_inbound', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_outbound', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_private_data', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_sic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_sic_data', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Acivities_included',
            new_name='Land_price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Activities_include',
            new_name='Package_name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Cities',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Exclusive',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Flight_inbound',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Flight_outbound',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Hotels',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Land_prise',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Totel_prise',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Transfer_detail',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='seperate_sic_or_private',
        ),
        migrations.AddField(
            model_name='hotel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='Package_discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='Totel_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hot_deal_package',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hotel',
            field=models.ManyToManyField(related_name='hotel', to='MeinPage.Hotel'),
        ),
        migrations.AddField(
            model_name='package',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='inclusive',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='meal_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='End_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='Start_date',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PriseOfPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totel_price', models.CharField(default='No Changes', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingprise', to='MeinPage.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='')),
                ('image_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_package', to='MeinPage.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_schedule', to='MeinPage.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_city_image', models.ImageField(upload_to='')),
                ('package_city', models.CharField(max_length=50)),
                ('package_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_city', to='MeinPage.Package')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='')),
                ('image_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_hotel', to='MeinPage.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Exclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelusion_data', models.CharField(max_length=200)),
                ('exclusion_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='MeinPage.Package')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packageforuser', to='MeinPage.Package'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbooking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvailabilityoFhotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_availeble', models.BooleanField(default=True)),
                ('hotel_price', models.CharField(default='No Changes', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='MeinPage.Booking')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availhotel', to='MeinPage.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=255)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='Flight_inbound_data',
            field=models.ManyToManyField(related_name='flight_inbound_data', to='MeinPage.Flight_inbound'),
        ),
        migrations.AddField(
            model_name='package',
            name='Flight_outbound_data',
            field=models.ManyToManyField(related_name='Flight_outbound_data', to='MeinPage.Flight_outbound'),
        ),
        migrations.AddField(
            model_name='package',
            name='Transfer_private',
            field=models.ManyToManyField(related_name='transfer_private', to='MeinPage.Transfer_private'),
        ),
        migrations.AddField(
            model_name='package',
            name='transfer_sic',
            field=models.ManyToManyField(related_name='transfer_sic_of_package', to='MeinPage.Transfer_sic'),
        ),
    ]
