# Generated by Django 2.2 on 2019-11-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0006_auto_20191116_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Package_discription',
            field=models.TextField(default='sdlfkjsdfj sdklfj dlsfkjdkls fjsdklfjls dkfjsdlfkjsdklfjsdfkjs'),
            preserve_default=False,
        ),
    ]
