# Generated by Django 2.2 on 2019-11-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0007_package_package_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Package_discription',
        ),
    ]
