# Generated by Django 2.2 on 2019-11-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0007_auto_20191120_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Cities',
            new_name='Land_price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Exclusive',
            new_name='Package_name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Land_prise',
            new_name='Totel_price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Totel_prise',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Hotels',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_city',
            field=models.CharField(default='adsf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.CharField(default='sdfasd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='Package_discription',
            field=models.TextField(default='sdfsdfsdfs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='discount',
            field=models.CharField(default='32', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(default='hgkjh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hot_deal_package',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='hotel',
            field=models.ManyToManyField(related_name='hotel', to='MeinPage.Hotel'),
        ),
        migrations.AlterField(
            model_name='package',
            name='End_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='Start_date',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='')),
                ('image_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_package', to='MeinPage.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_schedule', to='MeinPage.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Package_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_city_image', models.ImageField(upload_to='')),
                ('package_city', models.CharField(max_length=50)),
                ('package_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_city', to='MeinPage.Package')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='')),
                ('image_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_hotel', to='MeinPage.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Exclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelusion_data', models.CharField(max_length=200)),
                ('exclusion_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='MeinPage.Package')),
            ],
        ),
    ]
