# Generated by Django 2.2 on 2019-12-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0007_auto_20191202_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='End_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='Start_date',
            field=models.DateField(),
        ),
    ]
