# Generated by Django 2.2 on 2019-11-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0008_auto_20191120_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Transfer_detail',
            new_name='TransferPrivate',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Transfer_detail_seperate',
            new_name='Transfer_private',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='seperate_sic_or_private',
            new_name='Transfersic',
        ),
    ]
