# Generated by Django 2.2 on 2019-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0008_auto_20191202_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
