# Generated by Django 2.2 on 2019-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0009_package_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
