# Generated by Django 2.2 on 2019-11-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0009_package_package_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Land_prise',
            new_name='Land_price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Totel_prise',
            new_name='Totel_price',
        ),
    ]
