# Generated by Django 2.2 on 2019-11-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0009_auto_20191120_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='TransferPrivate',
            new_name='Transfer_detail_seperate',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Transfersic',
            new_name='Transfesic',
        ),
    ]
