# Generated by Django 2.2 on 2019-11-20 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0010_auto_20191120_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ManyToManyField(related_name='packageforuser', to='MeinPage.Package')),
                ('user', models.ManyToManyField(related_name='userbooking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
