# Generated by Django 2.2 on 2019-12-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0010_auto_20191202_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
