# Generated by Django 2.2 on 2019-11-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0010_auto_20191119_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_city',
            field=models.CharField(default='delhi', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hotel_cities',
        ),
    ]
