# Generated by Django 2.2 on 2019-11-19 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0011_auto_20191119_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_name', to='MeinPage.Package')),
            ],
        ),
    ]
