# Generated by Django 2.2 on 2019-11-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0012_package_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_city',
            name='Package_city_image',
            field=models.ImageField(default='index.jpeg', upload_to=''),
            preserve_default=False,
        ),
    ]
