# Generated by Django 2.2 on 2019-11-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0012_auto_20191120_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='review', max_length=20),
        ),
    ]
