# Generated by Django 2.2 on 2019-11-20 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0013_auto_20191120_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Acivities_included',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Activities_include',
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=255)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
