# Generated by Django 2.2 on 2019-11-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0014_auto_20191119_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Exclusive',
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.CharField(default='good', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Exclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelusion_data', models.CharField(max_length=200)),
                ('exclusion_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_package', to='MeinPage.Package')),
            ],
        ),
    ]
