# Generated by Django 2.2 on 2019-11-21 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0014_auto_20191120_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPackage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(max_length=255)),
                ('Package_discription', models.TextField()),
                ('Country', models.CharField(max_length=255)),
                ('Start_date', models.CharField(max_length=200)),
                ('End_date', models.CharField(max_length=255)),
                ('Flight_inbound', models.CharField(max_length=255)),
                ('Flight_outbound', models.CharField(max_length=255)),
                ('Flight_prise', models.CharField(max_length=255)),
                ('Land_price', models.CharField(max_length=255)),
                ('Totel_price', models.CharField(max_length=255)),
                ('Visa_included', models.CharField(max_length=255)),
                ('Meal_included', models.CharField(max_length=255)),
                ('Itnerary', models.TextField()),
                ('Company_details', models.CharField(max_length=255)),
                ('Transfer_private', models.CharField(max_length=255)),
                ('Freebies', models.CharField(max_length=255)),
                ('Transfer_detail_seperate', models.CharField(max_length=255)),
                ('Transfesic', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('hot_deal_package', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(default=datetime.datetime(2019, 11, 21, 9, 10, 29, 291182, tzinfo=utc))),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_id',),
                'get_latest_by': 'history_id',
            },
        ),
    ]
