# Generated by Django 2.2 on 2019-11-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0015_auto_20191119_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusions',
            name='exclusion_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='MeinPage.Package'),
        ),
    ]
