# Generated by Django 2.2 on 2019-11-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0015_historicalpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityoFhotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_availeble', models.BooleanField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='MeinPage.Booking')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availhotel', to='MeinPage.Hotel')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalPackage',
        ),
    ]
