# Generated by Django 2.2 on 2019-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0016_auto_20191121_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityofhotel',
            name='hotel_availeble',
            field=models.BooleanField(default=True),
        ),
    ]
