# Generated by Django 2.2 on 2019-11-21 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0019_auto_20191121_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityofhotel',
            name='hotel_price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PriseOfPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totel_price', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingprise', to='MeinPage.Booking')),
            ],
        ),
    ]
