# Generated by Django 2.2 on 2019-11-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0020_auto_20191121_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityofhotel',
            name='hotel_price',
            field=models.CharField(default='No Changes', max_length=20),
        ),
        migrations.AlterField(
            model_name='priseofpackage',
            name='totel_price',
            field=models.CharField(default='No Changes', max_length=20),
        ),
    ]
