# Generated by Django 2.2 on 2019-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0022_package_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
