# Generated by Django 2.2 on 2019-11-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0024_auto_20191121_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='visable',
            field=models.BooleanField(default=False),
        ),
    ]
