# Generated by Django 2.2 on 2019-11-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0026_auto_20191122_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
