# Generated by Django 2.2 on 2019-11-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0027_hotelquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotelquery',
        ),
    ]
