# Generated by Django 2.2 on 2019-11-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0029_auto_20191122_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
