# Generated by Django 2.2 on 2019-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0030_hotel_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_city',
            name='package_city_id',
        ),
        migrations.AddField(
            model_name='package',
            name='package_city_name',
            field=models.ManyToManyField(related_name='package_city_name', to='MeinPage.Package_city'),
        ),
    ]
