# Generated by Django 2.2 on 2019-11-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0031_auto_20191122_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_city_name',
        ),
        migrations.AddField(
            model_name='package_city',
            name='package_city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package_city', to='MeinPage.Package'),
            preserve_default=False,
        ),
    ]
