# Generated by Django 2.2 on 2019-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0032_auto_20191122_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_sic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_sic_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='transfer_sic',
            field=models.ManyToManyField(related_name='transfer_sic_of_package', to='MeinPage.Transfer_sic'),
        ),
    ]
