# Generated by Django 2.2 on 2019-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0033_auto_20191122_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_sic',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
