# Generated by Django 2.2 on 2019-11-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0034_transfer_sic_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_inbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_inbound', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_outbound', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_private',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_private_data', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='Flight_inbound',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Flight_outbound',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Transfer_private',
        ),
        migrations.AddField(
            model_name='package',
            name='Flight_inbound',
            field=models.ManyToManyField(related_name='flight_inbound_data', to='MeinPage.Flight_inbound'),
        ),
        migrations.AddField(
            model_name='package',
            name='Flight_outbound',
            field=models.ManyToManyField(related_name='Flight_outbound_data', to='MeinPage.Flight_outbound'),
        ),
        migrations.AddField(
            model_name='package',
            name='Transfer_private',
            field=models.ManyToManyField(related_name='transfer_private', to='MeinPage.Transfer_private'),
        ),
    ]
