# Generated by Django 2.2 on 2019-11-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0035_auto_20191123_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Flight_inbound',
            new_name='Flight_inbound_data',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Flight_outbound',
            new_name='Flight_outbound_data',
        ),
    ]
