# Generated by Django 2.2 on 2019-11-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeinPage', '0036_auto_20191123_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Transfesic',
        ),
    ]
